shellEmulator: true

trustPolicy: no-downgrade

packages:
  - services/*
  - wrappers/*
  - packages/*
  # Legacy directories - to be removed after migration verified
  - containers/*
  - functions/*
onlyBuiltDependencies:
  - esbuild
  - secp256k1
